package iisc.dsl.picasso.common;

import java.io.PrintWriter;
import java.util.HashMap;

public class HardCoded {
	public static boolean WorkingOnExpanded = false;
	public static boolean writeCosts = true;
	public static final int SanityConstant = 10;
	public static double maxUnderEstimate = 0.0;
	public static double minUnderEstimate = Double.MAX_VALUE;
	public static double sumUnderEstimate = 0.0;
	public static PrintWriter logEstimation = null;
	public final static boolean TEMPgeneratePCSTFiles = false;
	public static String queryTemp = "QT2";
	public final static boolean allIndex = false;  // Change if not AllIndex
	public static String serfCalPath = "H:\\AI-Setup\\Outputs\\";  // Change if not AllIndex
	public static String RQEP_expand;
	public static String allIndexString = "-AI";
	// calculateSERF , UnionPlansPCSTFiles = true ; generatePCSTFiles= false;
	public final static boolean calculateSERF = false; // Uses pcst files. Sets GlobalPCST to true.
	public final static boolean UnionPlansPCSTFiles = false; // pcst files are there for union of plans.
	public final static boolean generatePCSTFiles = false;
	// genDiagrams or doRQEP_Reduction is true. Both cannot be true at one instance.
	public final static boolean checkSERFForOriginalDiagram = false;
	public final static boolean doRQEP_Reduction = true;
	public final static boolean genDiagrams = !doRQEP_Reduction;
	public final static boolean readReducedDiagram = false;
	
	
	public static String[][] oldColumns = {{"c_acctbal","s_acctbal"}
	}; 
	public static String[][] newColumns_js_00 = {{}
	};
	public static String[][] newColumns_js_11 = {{"c_acctbal_js_1","s_acctbal_js_1"}
	};

	
	
	public static String[] oldIndexes = {"PK__NATION__2D27B809","PK__REGION__2C3393D0","PK__SUPPLIER__300424B4","PK__PART__2F10007B","PK__PARTSUPP__31EC6D26","PK__CUSTOMER__32E0915F","PK__ORDERS__35BCFE0A","PK__LINEITEM__34C8D9D1"};
	public static String[] newIndexes_Expand2 = {"PK__NATION_Expanded___7C1A6C5A","PK__REGION_Expanded___7B264821","PK__SUPPLIER_Expande__7EF6D905","PK__PART_Expanded_2__7E02B4CC","PK__PARTSUPP_Expande__00DF2177","PK__CUSTOMER_Expande__01D345B0","PK__ORDERS_Expanded___04AFB25B","PK__LINEITEM_Expande__03BB8E22"};
	public static String[] newIndexes_Expand3 = {"PK__NATION_Expanded___14E61A24","PK__REGION_Expanded___13F1F5EB","PK__SUPPLIER_Expande__17C286CF","PK__PART_Expanded_3__16CE6296","PK__PARTSUPP_Expande__19AACF41","PK__CUSTOMER_Expande__1A9EF37A","PK__ORDERS_Expanded___1D7B6025","PK__LINEITEM_Expande__1C873BEC"};
	public static String[] newIndexes_Expand4 = {"PK__NATION_Expanded___2DB1C7EE","PK__REGION_Expanded___2CBDA3B5","PK__SUPPLIER_Expande__308E3499","PK__PART_Expanded_4__2F9A1060","PK__PARTSUPP_Expande__32767D0B","PK__CUSTOMER_Expande__336AA144","PK__ORDERS_Expanded___36470DEF","PK__LINEITEM_Expande__3552E9B6"};
	public static String[] newIndexes_Expand5 = {"PK__NATION_Expanded___4B422AD5","PK__REGION_Expanded___4A4E069C","PK__SUPPLIER_Expande__4E1E9780","PK__PART_Expanded_5__4D2A7347","PK__PARTSUPP_Expande__5006DFF2","PK__CUSTOMER_Expande__50FB042B","PK__ORDERS_Expanded___53D770D6","PK__LINEITEM_Expande__52E34C9D"};
	public static String[] newIndexes_Expand6 = {"PK__NATION_Expanded___640DD89F","PK__REGION_Expanded___6319B466","PK__SUPPLIER_Expande__66EA454A","PK__PART_Expanded_6__65F62111","PK__PARTSUPP_Expande__68D28DBC","PK__CUSTOMER_Expande__69C6B1F5","PK__ORDERS_Expanded___6D9742D9","PK__LINEITEM_Expande__6CA31EA0"};

	public static String[] oldTableNames = {"[NATION]","[REGION]","[SUPPLIER]","[PART]","[PARTSUPP]","[CUSTOMER]","[ORDERS]","[LINEITEM]"};
	public static String[] RQEP_Expand = {"Expanded_2","Expanded_3","Expanded_4","Expanded_5","Expanded_6"};
	//public static String[] RQEP_Expand = {"js_0","js_1"};
	//public static String[] RQEP_Expand = {"js_1"};
	
	//public static String[] QTDValues = {"QT2","QT5","QT8","QT9","QT10","QT16","QT5_3D","QT8_3D","QT9_3D"};
	public static String[] QTDValues = {"QT2","QT5","QT8","QT9","QT10","QT16","ModifiedQT5"};  // DO NOT CHANGE THIS ORDER. allQueryTemplates and AllQueryTemplates are dependent on this order.
	public static String[] expandValues = {"_Expanded_0","_Expanded_2","_Expanded_3","_Expanded_4","_Expanded_5","_Expanded_6"};
	//public static String[] expandValues = {"_js","_js_1"};
	public static String[][] allQueryTemplates = {
			{
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part, supplier, partsupp, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp, supplier, nation, region where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey",
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part_Expanded_2, supplier_Expanded_2, partsupp_Expanded_2, nation_Expanded_2, region_Expanded_2 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp_Expanded_2, supplier_Expanded_2, nation_Expanded_2, region_Expanded_2 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey",
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part_Expanded_3, supplier_Expanded_3, partsupp_Expanded_3, nation_Expanded_3, region_Expanded_3 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp_Expanded_3, supplier_Expanded_3, nation_Expanded_3, region_Expanded_3 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey",
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part_Expanded_4, supplier_Expanded_4, partsupp_Expanded_4, nation_Expanded_4, region_Expanded_4 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp_Expanded_4, supplier_Expanded_4, nation_Expanded_4, region_Expanded_4 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey",
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part_Expanded_5, supplier_Expanded_5, partsupp_Expanded_5, nation_Expanded_5, region_Expanded_5 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp_Expanded_5, supplier_Expanded_5, nation_Expanded_5, region_Expanded_5 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey",
				"select s_acctbal, s_name, n_name, p_partkey, p_mfgr, s_address, s_phone, s_comment from part_Expanded_6, supplier_Expanded_6, partsupp_Expanded_6, nation_Expanded_6, region_Expanded_6 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and p_retailprice :varies and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost <= ( select min(ps_supplycost) from partsupp_Expanded_6, supplier_Expanded_6, nation_Expanded_6, region_Expanded_6 where p_partkey = ps_partkey and s_suppkey = ps_suppkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'EUROPE' and ps_supplycost :varies ) order by s_acctbal desc, n_name, s_name, p_partkey"
			},
			{
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer, orders,	lineitem, supplier, nation, region where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_2, orders_Expanded_2,	lineitem_Expanded_2, supplier_Expanded_2, nation_Expanded_2, region_Expanded_2 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_3, orders_Expanded_3,	lineitem_Expanded_3, supplier_Expanded_3, nation_Expanded_3, region_Expanded_3 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_4, orders_Expanded_4,	lineitem_Expanded_4, supplier_Expanded_4, nation_Expanded_4, region_Expanded_4 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_5, orders_Expanded_5,	lineitem_Expanded_5, supplier_Expanded_5, nation_Expanded_5, region_Expanded_5 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_6, orders_Expanded_6,	lineitem_Expanded_6, supplier_Expanded_6, nation_Expanded_6, region_Expanded_6 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies group by n_name order by revenue desc"
			},
			{
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part, supplier, lineitem, orders, customer, nation n1, nation n2, region where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_2, supplier_Expanded_2, lineitem_Expanded_2, orders_Expanded_2, customer_Expanded_2, nation_Expanded_2 n1, nation_Expanded_2 n2, region_Expanded_2 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_3, supplier_Expanded_3, lineitem_Expanded_3, orders_Expanded_3, customer_Expanded_3, nation_Expanded_3 n1, nation_Expanded_3 n2, region_Expanded_3 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_4, supplier_Expanded_4, lineitem_Expanded_4, orders_Expanded_4, customer_Expanded_4, nation_Expanded_4 n1, nation_Expanded_4 n2, region_Expanded_4 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_5, supplier_Expanded_5, lineitem_Expanded_5, orders_Expanded_5, customer_Expanded_5, nation_Expanded_5 n1, nation_Expanded_5 n2, region_Expanded_5 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_6, supplier_Expanded_6, lineitem_Expanded_6, orders_Expanded_6, customer_Expanded_6, nation_Expanded_6 n1, nation_Expanded_6 n2, region_Expanded_6 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_orderdate between '1995-01-01' and '1996-12-31' and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year "	
			},
			{
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part, supplier, lineitem, partsupp, orders, nation where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_2, supplier_Expanded_2, lineitem_Expanded_2, partsupp_Expanded_2, orders_Expanded_2, nation_Expanded_2 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_3, supplier_Expanded_3, lineitem_Expanded_3, partsupp_Expanded_3, orders_Expanded_3, nation_Expanded_3 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_4, supplier_Expanded_4, lineitem_Expanded_4, partsupp_Expanded_4, orders_Expanded_4, nation_Expanded_4 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_5, supplier_Expanded_5, lineitem_Expanded_5, partsupp_Expanded_5, orders_Expanded_5, nation_Expanded_5 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_6, supplier_Expanded_6, lineitem_Expanded_6, partsupp_Expanded_6, orders_Expanded_6, nation_Expanded_6 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies ) as profit group by n_name, o_year order by n_name, o_year desc "
			},
			{
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer, orders, lineitem, nation where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc ",
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer_Expanded_2, orders_Expanded_2, lineitem_Expanded_2, nation_Expanded_2 where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc ",
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer_Expanded_3, orders_Expanded_3, lineitem_Expanded_3, nation_Expanded_3 where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc ",
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer_Expanded_4, orders_Expanded_4, lineitem_Expanded_4, nation_Expanded_4 where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc ",
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer_Expanded_5, orders_Expanded_5, lineitem_Expanded_5, nation_Expanded_5 where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc ",
				"select c_custkey, c_name, sum(l_extendedprice * (1 - l_discount)) as revenue, c_acctbal, n_name, c_address, c_phone, c_comment from customer_Expanded_6, orders_Expanded_6, lineitem_Expanded_6, nation_Expanded_6 where c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate >= '1993-10-01' and o_orderdate < '1994-01-01' and c_nationkey = n_nationkey and c_acctbal :varies and l_extendedprice :varies group by c_custkey, c_name, c_acctbal, c_phone, n_name, c_address, c_comment order by revenue desc "
				
			},
			{
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp, part where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp_Expanded_2, part_Expanded_2 where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier_Expanded_2 where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp_Expanded_3, part_Expanded_3 where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier_Expanded_3 where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp_Expanded_4, part_Expanded_4 where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier_Expanded_4 where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp_Expanded_5, part_Expanded_5 where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier_Expanded_5 where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
				"select p_brand, p_type, p_size, count(distinct ps_suppkey) as supplier_cnt from partsupp_Expanded_6, part_Expanded_6 where p_partkey = ps_partkey and p_retailprice :varies and ps_suppkey in ( select s_suppkey from supplier_Expanded_6 where s_acctbal :varies ) group by p_brand, p_type, p_size order by supplier_cnt desc, p_brand, p_type, p_size ",
			},
			{
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_js, orders, lineitem, supplier_js, nation, region where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_acctbal = s_acctbal and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and l_extendedprice :varies and o_totalprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_js, orders, lineitem, supplier_js, nation, region where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_acctbal_js_1 = s_acctbal_js_1 and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and l_extendedprice :varies and o_totalprice :varies group by n_name order by revenue desc"
			}/*,
			{
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer, orders,	lineitem, supplier, nation, region where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_2, orders_Expanded_2,	lineitem_Expanded_2, supplier_Expanded_2, nation_Expanded_2, region_Expanded_2 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_3, orders_Expanded_3,	lineitem_Expanded_3, supplier_Expanded_3, nation_Expanded_3, region_Expanded_3 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_4, orders_Expanded_4,	lineitem_Expanded_4, supplier_Expanded_4, nation_Expanded_4, region_Expanded_4 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_5, orders_Expanded_5,	lineitem_Expanded_5, supplier_Expanded_5, nation_Expanded_5, region_Expanded_5 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc",
				"select	n_name,	sum(l_extendedprice * (1 - l_discount)) as revenue from	customer_Expanded_6, orders_Expanded_6,	lineitem_Expanded_6, supplier_Expanded_6, nation_Expanded_6, region_Expanded_6 where c_custkey = o_custkey and l_orderkey = o_orderkey and l_suppkey = s_suppkey and c_nationkey = s_nationkey and s_nationkey = n_nationkey and n_regionkey = r_regionkey and r_name = 'ASIA' and o_orderdate >= '1994-01-01' and o_orderdate < '1995-01-01' and c_acctbal :varies and s_acctbal :varies and l_extendedprice :varies group by n_name order by revenue desc"
			},
			{
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part, supplier, lineitem, orders, customer, nation n1, nation n2, region where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_2, supplier_Expanded_2, lineitem_Expanded_2, orders_Expanded_2, customer_Expanded_2, nation_Expanded_2 n1, nation_Expanded_2 n2, region_Expanded_2 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_3, supplier_Expanded_3, lineitem_Expanded_3, orders_Expanded_3, customer_Expanded_3, nation_Expanded_3 n1, nation_Expanded_3 n2, region_Expanded_3 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_4, supplier_Expanded_4, lineitem_Expanded_4, orders_Expanded_4, customer_Expanded_4, nation_Expanded_4 n1, nation_Expanded_4 n2, region_Expanded_4 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_5, supplier_Expanded_5, lineitem_Expanded_5, orders_Expanded_5, customer_Expanded_5, nation_Expanded_5 n1, nation_Expanded_5 n2, region_Expanded_5 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year ",
				"select	o_year,	sum(case when nation = 'BRAZIL' then volume	else 0	end) / sum(volume) from ( select YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) as volume, n2.n_name as nation from part_Expanded_6, supplier_Expanded_6, lineitem_Expanded_6, orders_Expanded_6, customer_Expanded_6, nation_Expanded_6 n1, nation_Expanded_6 n2, region_Expanded_6 where p_partkey = l_partkey and s_suppkey = l_suppkey and l_orderkey = o_orderkey and o_custkey = c_custkey and c_nationkey = n1.n_nationkey and n1.n_regionkey = r_regionkey and r_name = 'AMERICA' and s_nationkey = n2.n_nationkey and o_totalprice :varies and p_type = 'ECONOMY ANODIZED STEEL' and s_acctbal :varies and l_extendedprice :varies ) as all_nations group by o_year order by o_year "
			},
			{
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part, supplier, lineitem, partsupp, orders, nation where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_2, supplier_Expanded_2, lineitem_Expanded_2, partsupp_Expanded_2, orders_Expanded_2, nation_Expanded_2 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_3, supplier_Expanded_3, lineitem_Expanded_3, partsupp_Expanded_3, orders_Expanded_3, nation_Expanded_3 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_4, supplier_Expanded_4, lineitem_Expanded_4, partsupp_Expanded_4, orders_Expanded_4, nation_Expanded_4 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_5, supplier_Expanded_5, lineitem_Expanded_5, partsupp_Expanded_5, orders_Expanded_5, nation_Expanded_5 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc ",
				"select n_name, o_year, sum(amount) from ( 	select n_name, YEAR(o_orderdate) as o_year, l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount from part_Expanded_6, supplier_Expanded_6, lineitem_Expanded_6, partsupp_Expanded_6, orders_Expanded_6, nation_Expanded_6 where s_suppkey = l_suppkey and ps_suppkey = l_suppkey and ps_partkey = l_partkey and p_partkey = l_partkey and o_orderkey = l_orderkey and s_nationkey = n_nationkey and p_name like '%green%' and s_acctbal :varies and ps_supplycost :varies and l_extendedprice :varies) as profit group by n_name, o_year order by n_name, o_year desc "
			}*/
	};
	public final static HashMap<String, String[]> AllQueryTemplates = new HashMap();
	public final static HashMap<String, String[]> AllQueryTemplatesColumns = new HashMap();
	public final static HashMap<String, String[]> AllQueryTemplatesNewColumns_js_00 = new HashMap();
	public final static HashMap<String, String[]> AllQueryTemplatesNewColumns_js_11 = new HashMap();

	
	static
	{
		AllQueryTemplates.put("QT2", allQueryTemplates[0]);
		AllQueryTemplates.put("QT5", allQueryTemplates[1]);
		AllQueryTemplates.put("QT8", allQueryTemplates[2]);
		AllQueryTemplates.put("QT9", allQueryTemplates[3]);
		AllQueryTemplates.put("QT10", allQueryTemplates[4]);
		AllQueryTemplates.put("QT16", allQueryTemplates[5]);
		AllQueryTemplates.put("ModifiedQT5", allQueryTemplates[6]);
		
		AllQueryTemplatesColumns.put("ModifiedQT5", oldColumns[0]);
		AllQueryTemplatesNewColumns_js_00.put("ModifiedQT5", newColumns_js_00[0]);
		AllQueryTemplatesNewColumns_js_11.put("ModifiedQT5", newColumns_js_11[0]);
		
	}
	
	
}
